name: sedd
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - gds-tools=1.4.0.31=0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2022.3.0.22=0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.27.2
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - beartype==0.14.1
    - better-abc==0.0.3
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmake==3.25.0
    - datasets==2.17.1
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - fancy-einsum==0.0.3
    - filelock==3.9.0
    - flash-attn==2.2.2
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - huggingface-hub==0.21.1
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - idna==3.4
    - jaxtyping==0.2.25
    - jinja2==3.1.2
    - lit==15.0.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - networkx==3.2.1
    - ninja==1.11.1.1
    - numpy==1.24.1
    - omegaconf==2.3.0
    - packaging==23.2
    - pandas==2.2.1
    - pillow==10.2.0
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyarrow==15.0.0
    - pyarrow-hotfix==0.6
    - pygments==2.17.2
    - python-dateutil==2.8.2
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests==2.28.1
    - rich==13.7.0
    - safetensors==0.4.2
    - sentry-sdk==1.40.6
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - submitit==1.5.1
    - sympy==1.12
    - tokenizers==0.15.2
    - torch==2.0.1+cu118
    - torchaudio==2.0.2+cu118
    - torchvision==0.15.2+cu118
    - tqdm==4.66.2
    - transformer-lens==1.14.0
    - transformers==4.38.1
    - triton==2.0.0
    - typeguard==2.13.3
    - typing-extensions==4.8.0
    - tzdata==2024.1
    - urllib3==1.26.13
    - wandb==0.16.3
    - xxhash==3.4.1
    - yarl==1.9.4
prefix: /home/aaron/anaconda3/envs/sedd
